# Generated by Django 5.0.1 on 2026-01-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCodeModificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.TextField(blank=True, null=True)),
                ('sap_part_code', models.TextField(blank=True, null=True)),
                ('new_material_description', models.TextField(blank=True, null=True)),
                ('hsn_code', models.TextField(blank=True, null=True)),
                ('from_state_to_state', models.TextField(blank=True, null=True)),
                ('tax', models.TextField(blank=True, null=True)),
                ('sales_views', models.TextField(blank=True, null=True)),
                ('supplying_plant', models.TextField(blank=True, null=True)),
                ('receiving_plant', models.TextField(blank=True, null=True)),
                ('tax_indication_of_the_material', models.TextField(blank=True, null=True)),
                ('procurement_type', models.TextField(blank=True, null=True)),
                ('activate_storage_location', models.TextField(blank=True, null=True)),
                ('production_version_update', models.TextField(blank=True, null=True)),
                ('quality_management', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sap_remarks_only_for_sap_validation_member_access', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('sap_validation_status', models.TextField(blank=True, null=True)),
                ('last_returned_by_role', models.TextField(blank=True, null=True)),
                ('attachment_urls', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('sap_validated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
